---

- name: Create moteino user
  user:
    state: present
    name: "{{moteino_username}}"
    home: "{{moteino_home_dir}}"
    groups: "dialout"
    createhome: yes
    shell: "/bin/bash"
  tags: [ "gateway", "user" ]

- name: Clone moteino gateway git repository
  git:
    repo: "{{gateway_repo_url}}"
    dest: "{{gateway_repo_dir}}"
    accept_hostkey: yes
    update: no
  tags: [ "gateway" ]

- name: Update moteino gateway git repository
  git:
    repo: "{{gateway_repo_url}}"
    dest: "{{gateway_repo_dir}}"
    accept_hostkey: yes
    update: yes
  when: update|bool
  tags: [ "gateway", "update" ]

- name: Install required Node.JS packages
  npm:
    path: "{{gateway_repo_dir}}"
    state: present
  tags: [ "gateway", "nodejs" ]

- name: Ensure gateway dir is owned by correct user
  file:
    state: directory
    path: "{{gateway_repo_dir}}"
    owner: "{{moteino_username}}"
    group: "{{moteino_username}}"
    recurse: yes
  tags: [ "gateway" ]

- name: Check if log file exists
  stat:
    path: "{{gateway_log_filename}}"
  register: logfile
  tags: [ "gateway", "syslog" ]

- name: Create an empty log file
  file:
    path: "{{gateway_log_filename}}"
    state: touch
    owner: "{{moteino_username}}"
    group: "adm"
    mode: 0640
  when: not logfile.stat.exists
  notify: Restart rsyslog
  tags: [ "gateway", "syslog" ]

- name: Install logrotate configuration file from template
  template:
    src: "{{item}}.j2"
    dest: "/{{item}}"
    owner: root
    group: root
    mode: 644
  with_items:
    - "etc/logrotate.d/moteino-gateway.conf"
  tags: [ "gateway", "syslog", "logrotate" ]

- name: Install rsyslog configuration file from template
  template:
    src: "{{item}}.j2"
    dest: "/{{item}}"
    owner: root
    group: root
    mode: 644
  with_items:
    - "etc/rsyslog.d/moteino-gateway.conf"
  notify: Restart rsyslog
  tags: [ "gateway", "syslog" ]

- name: Install systemd service file from template
  template:
    src: "{{item}}.j2"
    dest: "/{{item}}"
    owner: root
    group: root
    mode: 644
  with_items:
    - "etc/systemd/system/moteino-gateway.service"
  notify: Restart moteino-gateway
  tags: [ "gateway", "service" ]

- name: Enable gateway.js systemd service
  service:
    name: moteino-gateway
    enabled: yes
  notify: Restart moteino-gateway 
  tags: [ "gateway", "service" ]

- name: Install nginx virtual host configuration file from template
  template:
    src: "{{item}}.j2"
    dest: "/{{item}}"
    owner: root
    group: root
    mode: 644
  with_items:
    - "etc/nginx/sites-available/moteino-gateway.conf"
  notify: Restart nginx
  tags: [ "gateway", "nginx" ]

- name: Enable nginx virtual host
  file:
    state: link
    src: "/etc/nginx/sites-available/{{item}}.conf"
    dest: "/etc/nginx/sites-enabled/{{item}}"
  with_items:
    - "moteino-gateway"
  notify: Restart nginx
  tags: [ "gateway", "nginx" ]

- name: Disable nginx default virtual host
  file:
    state: absent
    path: "/etc/nginx/sites-enabled/default"
  notify: Restart nginx
  tags: [ "gateway", "nginx" ]

- name: Enable nginx systemd service
  service:
    name: nginx
    enabled: yes
  notify: Restart nginx
  tags: [ "gateway", "nginx", "service" ]
