---
- hosts: all

  vars:
    packaging_packages:
      # base
      - apt-transport-https
      - autofs
      - cifs-utils
      - curl
      - git
      - openssh-server
      - vim-nox
      - unzip
      # admin
      - htop
      - iftop
      - iotop
      - sysstat
      - tmux
      - traceroute
      # application
      - nginx

  vars_prompt:
    - name: "wifi_ssid"
      prompt: "Enter wifi SSID"
      private: no

    - name: "wifi_psk"
      prompt: "Enter wifi PSK"
      private: no
      #confirm: yes
      #encrypt: "pbkdf2_digest"
      #salt_size: 8

  roles:
    - tweaks
    - wifi
    - packaging
    - nodejs
