---

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Restart moteino-gateway
  service:
    name: moteino-gateway
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
